version: "3.7"
services:
    jupyter:
        build:
            context: $PATH_TO_PROJECT
            dockerfile: $PATH_TO_PROJECT/build_tools/docker/poetry-notebook/Dockerfile
            args:
                - POETRY_VERSION=$POETRY_VERSION
                - CONTEXT_DIR=./build_tools/docker/poetry-notebook
        image: jupyter:0.11
        restart: always
        user: root
        environment:
            - GRANT_SUDO=yes
            - UID=$UID
            - GID=$GID
            - PASSWORD=$JUPYTER_PASSWORD
            - TZ=Asia/Tokyo
            - ENV=BASE
            - RUN_STREAMLIT=$RUN_STREAMLIT
            - STREAMLIT_APP_NAME=$STREAMLIT_APP_NAME
            - RUN_DASHBOARD=$RUN_DASHBOARD
            - DASHBOARD_CONFIG_NAME=$DASHBOARD_CONFIG_NAME
        ports:
            - $JUPYTER_PORT:8888
            - $STREAMLIT_PORT:8501
            - $DASHBOARD_PORT:8050
        volumes:
            - $PATH_TO_PROJECT:/home/jovyan/work
            - $PATH_TO_DATA:/home/jovyan/work/data
